# Site settings
title: Andrew Carson Gay
email: gay.carson.andrew@gmail.com
description: A small blog with all of my creations
baseurl: ""
url: "http://andrewcarsongay.com"
twitter_username: "AndrewCGay"
linkedin_username: "andrewcarsongay"
avatar: "http://i1027.photobucket.com/albums/y332/andrewcarsongay/family_zpsgwsi0iew.jpg?t=1435766655" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Andrew Carson Gay" # Set default author name
      categories: "general"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
